### ISSUE TITLE
MediaTek 调速器在 8100 上工作异常

### ISSUE THREAD

**Issue by ppjysa** [NalanyinyunGakuen/Apodidae#11]
# 设备信息
定制 UI 版本: miui13.0.11
Android 版本: 12
设备名称: 红米note11tpro
SoC 名称: 8100
# 问题描述
使用ct时gpu频率在822不会改变
![Screenshot_2023-02-16-01-18-20-797_xyz chenzyadb cu_toolbox](https://user-images.githubusercontent.com/125581215/219409253-a638c3f8-6865-4902-8966-aafbcd30669b.jpg)

#  #确认
我确认已经对照兼容性指南排查问题

**Comment by naranyinyun** [comment]
MIUI默认的调度在有负载是也会跑到800MHz左右，可以试试手机静置无负载再看数值

**Comment by ppjysa** [comment]
是所有场景下都是822 静止不动也是的 锁死了

**Comment by naranyinyun** [comment]
> 是所有场景下都是822 静止不动也是的 锁死了

用的是什么版本的 Cutoolbox 呢，我试了一下没复现出来

日志也请提供一下

**Comment by naranyinyun** [comment]
试出来了，不过看起来不像 Apodidae 配置文件的问题，建议先使用 dimensity8100_GPUGOVE_disable.zip 内的配置文件

**Comment by ppjysa** [comment]
好像是ct本身8100调频器存在一些问题 只要先点一下启动调度 无论是否使用调度文件都会锁822 把配置文件里面调频器关了 必须把软件卸载重启 先把文件导入进去再按开始调度 他才会关
![Screenshot_2023-02-17-00-14-06-660_xyz chenzyadb cu_toolbox](https://user-images.githubusercontent.com/125581215/219424703-05a721ed-83ff-435e-b315-92d9f975bec4.jpg)
![Uploading Screenshot_2023-02-17-00-14-01-197_xyz.chenzyadb.cu_toolbox.jpg…]()

**Comment by ppjysa** [comment]
简单来说 就是ct软件可能在8100调频器上有问题 替换文件不起作用 必须卸载重启重装 在调度未启动的情况下先导入文件 再启动才会把gpu调频器功能关闭 否则一直卡822 不论是否使用文件

**Comment by naranyinyun** [comment]
那建议先 disable GPU 部分，我在下个release会禁用GPU部分
有可能gpufreqv2的设备控制都有问题，我没其他的调试设备

**Comment by naranyinyun** [comment]
如果没有其他问题，我就close这个issue了，问题将被记录至project

**Comment by ppjysa** [comment]
好的 close 配置文件必须卸载重启重装ct才会生效 起码在gpu这部分是这样的

**Comment by ppjysa** [comment]
不用配置文件 使用原版ct也会锁822的

**Comment by naranyinyun** [comment]
那具体要等上游修复了

**Comment by naranyinyun** [comment]
Cutoolbox更新了7.3.6_Alpha，可以试试是否还锁死800MHz
