### ISSUE TITLE
红米note8pro  flyme10掉帧

### ISSUE THREAD

**Issue by llkono0y** [NalanyinyunGakuen/Apodidae#19]
### Bug 描述

         在移植的flyme上出现掉帧的情况，我不知道是不是包的问题还是其他其他问题
          我尝试过更换yc调度，以及加上两个它的子模块，尝试过换ct版本和ap版本，最新版本和稳定版，尝试scene在线，这些都失败了。我也尝试回到MIUI重刷包，然而还是掉帧。可能真的是包的问题
           在尝试ap版本的过程中，都用最新版本比老版本稳定一些。
           目前掉帧体现在，小窗动画，下拉通知，控制中心，打开关闭应用，应用内滑动

### 复现步骤

刷入flyme10，刷入调度，体验掉帧

### 版本信息

Android13    flyme10
aq   3.1最新

**Comment by naranyinyun** [comment]
关于 Apodidae V3 以后卡顿的问题是 Cutoolbox V7.5.* 造成的, Android13 我们在类原生ROM上调试正常    
考虑到 Uperf 和 Scene 同样的卡顿情况, 我们初步认为是 ROM 问题  
希望可以使用小米 Kite 或 Scene 提供较为完整的数据以便排查问题   
据我们了解到的来看, Flyme 在 N8P 上都有较为显著的卡顿现象

**Comment by llkono0y** [comment]
上午我做了以下测试






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "naranyinyun/Apodidae"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月16日(星期天) 凌晨0:36
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [naranyinyun/Apodidae] 红米note8pro  flyme10掉帧 (Issue #19)





 
关于 Apodidae V3 以后卡顿的问题是 Cutoolbox V7.5.* 造成的, Android13 我们在类原生ROM上调试正常
 考虑到 Uperf 和 Scene 同样的卡顿情况, 我们初步认为是 ROM 问题
 希望可以使用小米 Kite 或 Scene 提供较为完整的数据以便排查问题

**Comment by llkono0y** [comment]
[测试.zip](https://github.com/naranyinyun/Apodidae/files/11240959/default.zip)

**Comment by naranyinyun** [comment]
> [测试.zip](https://github.com/naranyinyun/Apodidae/files/11240959/default.zip)

目前看来是瞬时高负载大核频率低，但小核1200MHz 大核1085MHz 也不至于掉到10fps ，还是包的问题大

**Comment by llkono0y** [comment]
欧克
内核更换会带来改变吗


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "naranyinyun/Apodidae"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月16日(星期天) 下午3:19
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [naranyinyun/Apodidae] 红米note8pro  flyme10掉帧 (Issue #19)





  
测试.zip
  
目前看来是瞬时高负载大核频率低，但小核1200MHz 大核1085MHz 也不至于掉到10fps ，还是包的问题大

**Comment by naranyinyun** [comment]
@llkono0y 应该不会，而且 Unofficial Kernel 还可能导致无法使用 Apodidae

**Comment by llkono0y** [comment]
Nova Kernel？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "naranyinyun/Apodidae"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月16日(星期天) 下午3:48
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [naranyinyun/Apodidae] 红米note8pro  flyme10掉帧 (Issue #19)





 
@llkono0y 应该不会，而且 Unofficial Kernel 还可能导致无法使用 Apodidae

**Comment by naranyinyun** [comment]
@llkono0y Nova Kernel 应该可以

**Comment by llkono0y** [comment]
谢谢解答，我有空试试




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "naranyinyun/Apodidae"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月16日(星期天) 下午3:58
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [naranyinyun/Apodidae] 红米note8pro  flyme10掉帧 (Issue #19)





 
@llkono0y Nova Kernel 应该可以
